### ISSUE TITLE
Sample startup failed

### ISSUE THREAD

**Issue by AutismPatient** [sfreiberg/progress#4]

**Comment by sfreiberg** [comment]
Can you be more specific? What problem are you seeing? I just tested both the example in the README and the example_test and both work fine. Without more information I won't be able to help.

**Comment by AutismPatient** [comment]
![QQ图片20191025092209](https://user-images.githubusercontent.com/37021551/67536291-0c9ea280-f709-11e9-9642-c7e8e4a5022b.png)

Why does authorization fail

**Comment by sfreiberg** [comment]
You have to replace token with a real token from Slack and also change the channel to one that exists in your slack account.

**Comment by AutismPatient** [comment]
Where do I get the token

**Comment by sfreiberg** [comment]
https://slack.com/help/articles/215770388-create-and-regenerate-api-tokens

**Comment by AutismPatient** [comment]
I want to know what you set the token for. Is the progress bar directly related to the token

**Comment by sfreiberg** [comment]
You have to have a slack account and the token allows you to post to slack.
